targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
      json_serializable:
        generate_for:
          - '**/entities/**.dart'
          - '**/data/**.dart'
        options:
          checked: true
      freezed:
        generate_for:
          - '**/entities/**.dart'
          - '**/data/**.dart'
