name: iapetus
description: A Pandora JSON API client.
version: 0.1.0
homepage: https://github.com/EpimetheusMusicPlayer/iapetus

publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  ## Language
  meta: ^1.7.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

  ## I/O
  http: ^0.13.4

  ## Encryption
  blowfish_ecb: ^0.1.0

  ## Identification
  uuid: ^3.0.6
  android_device_id_generator: ^0.1.1

dev_dependencies:
  ## Language
  lint: ^1.8.2

  ## Building
  build_runner: ^2.1.11

  ## Code generation
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
