name: iapetus
description: A Pandora JSON API client.
version: 0.1.0
homepage: https://github.com/EpimetheusMusicPlayer/iapetus

publish_to: none

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  ## Language
  meta: ^1.7.0
  freezed_annotation: ^0.14.3

  ## Data structures
  collection: ^1.15.0

  ## I/O
  http: ^0.13.3

  ## Encryption
  blowfish_ecb: ^0.1.0

  ## Identification
  uuid: ^3.0.4
  android_device_id_generator: ^0.1.1

dev_dependencies:
  ## Language
  lint: ^1.5.3

  ## Building
  build_runner: ^2.1.1

  ## Code generation
  freezed: ^0.14.4
  json_serializable: ^5.0.0