name: iapetus
description: A Pandora JSON API client.
version: 0.1.0
homepage: https://github.com/EpimetheusMusicPlayer/iapetus

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ## Language
  meta: ^1.8.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  ## I/O
  http: ^0.13.5

  ## Encryption
  blowfish_ecb: ^0.1.0

  ## Identification
  uuid: ^3.0.7
  android_device_id_generator: ^0.1.1

dev_dependencies:
  ## Language
  lint: ^2.0.1

  ## Building
  build_runner: ^2.3.3

  ## Code generation
  freezed: ^2.3.2
  json_serializable: ^6.6.1
